spring:
  application:
    name: atm-service

server:
  port: 8082
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000

feign:
  hystrix:
    enabled: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
      fetchRegistry: true
  instance:
    preferIpAddress: true
  server:
    eviction-interval-timer-in-ms: 1000
  