spring:
  application:
    name: gateway-service
  zipkin:
    baseUrl: http://localhost:9411/

server:
  port: 8084
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
      fetchRegistry: true
  instance:
    preferIpAddress: true
  server:
    eviction-interval-timer-in-ms: 1000

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    atm:
      path: /atm/**
      serviceId: atm-service
      strip-prefix: false
    bank:
      path: /bank/**
      serviceId: bank-service
      strip-prefix: false