server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
  instance:
    hostname: localhost         #${discovery.hostname:localhost}

management:
  security:
    enabled: false
  
spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"  

spring:
  profiles: dev
  application:
     name: discovery-service
  thymeleaf:
    enabled: false
        
spring:
  profiles: docker
  application:
     name: discovery-service
  thymeleaf:
    enabled: false
    

    