server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: true
  instance:
    hostname: localhost         #${discovery.hostname:localhost}
  healthcheck:
      enabled: true

management:
  security:
    enabled: false
  
spring:
  main:
    banner-mode: "off" 
  application:
    name: discovery-service 

