

server:
  port: 8090
  
feign:
    hystrix:       
        enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: none  
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2 
  main:
    banner-mode: "off"     
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # using eureka instead of localhost
    instance:
      leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
      preferIpAddress: true
      appname: productservice

logging:
  file: boot_example.log
  org.hibernate: INFO
  org.hibernate.SQL: DEBUG