spring:
  application:
    name: atm-service
  zipkin:
    baseUrl: http://zipkin:9411/
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/microserviceexample/protocol/openid-connect/certs
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: testDB
      username: user
      password: user

server:
  port: 8082
  
bank-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000

feign:
  hystrix:
    enabled: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka,http://eureka-server-2:8762/eureka
      fetchRegistry: true
  instance:
    preferIpAddress: true
  server:
    eviction-interval-timer-in-ms: 1000

management:
  endpoints:
    web:
      base-path: /atm
      exposure:
        include: "*"