spring:
  application:
    name: atm-service
  zipkin:
    baseUrl: http://localhost:9411/
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/auth/realms/microserviceexample/protocol/openid-connect/certs

server:
  port: 8082
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000

feign:
  hystrix:
    enabled: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
      fetchRegistry: true
  instance:
    preferIpAddress: true
  server:
    eviction-interval-timer-in-ms: 1000

management:
  endpoints:
    web:
      base-path: /atm
      exposure:
        include: "*"