spring:
  application:
    name: bank-service
  zipkin:
    baseUrl: http://localhost:9411/
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/microserviceexample/protocol/openid-connect/certs
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank_db

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
      fetchRegistry: true
  instance:
    preferIpAddress: true
  server:
    eviction-interval-timer-in-ms: 1000
    
management:
  endpoints:
    web:
      base-path: /bank
      exposure:
        include: "*"