spring:
  application:
    name: eureka-server-1
  zipkin:
    baseUrl: http://localhost:9411/
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
    registerWithEureka: false
    fetchRegistry: false