apiVersion: v1
kind: Service
metadata:
  labels:
    app: atm-service
  name: atm-service
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    app: atm-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: atm-service
  name: atm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atm-service
  strategy: {}
  template:
    metadata:
      labels:
        app.network/private-cloud-network: "true"
        app: atm-service
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: dev
        - name: spring.cloud.config.uri
          value: http://config-server:8888
        image: atm-service:latest
        imagePullPolicy: Never
        name: atm-service
        ports:
        - containerPort: 8082
      restartPolicy: Always