#Server port
server:
  port: 8888
 
#Git repo config
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/reactkart/springmicro
          cloneOnStart: true
          searchPaths: config_server_files